---
version: "2.1"
services:
  code-server:
    image: 3dsmc
    container_name: 3dsmc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./app/config:/config
      - ./files:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
